# Generated by Django 5.2.8 on 2025-11-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_approval_worker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Approval",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужчина"), ("F", "Женщина")], default="M", max_length=1
            ),
            preserve_default=False,
        ),
    ]
