# Generated by Django 5.2.8 on 2025-12-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_approval_delete_worker_profile_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
    ]
