# Generated by Django 5.2.8 on 2025-11-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0006_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-date"]},
        ),
        migrations.RemoveField(
            model_name="history",
            name="new_place_item",
        ),
        migrations.RemoveField(
            model_name="history",
            name="old_place_item",
        ),
        migrations.AddField(
            model_name="history",
            name="new_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="old_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
