# Generated by Django 5.2.8 on 2025-11-18 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0007_alter_history_options_remove_history_new_place_item_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="new_address",
        ),
        migrations.RemoveField(
            model_name="history",
            name="old_address",
        ),
        migrations.AddField(
            model_name="history",
            name="new_place",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_new_place",
                to="warehouse.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="new_stock",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_new_stock",
                to="warehouse.stock",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="new_zone",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_new_zone",
                to="warehouse.zone",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="old_place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_old_place",
                to="warehouse.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="old_stock",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_old_stock",
                to="warehouse.stock",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="old_zone",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_as_old_zone",
                to="warehouse.zone",
            ),
            preserve_default=False,
        ),
    ]
