# Generated by Django 5.2.8 on 2025-11-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0008_remove_history_new_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="new_stock",
        ),
        migrations.RemoveField(
            model_name="history",
            name="new_zone",
        ),
        migrations.RemoveField(
            model_name="history",
            name="old_stock",
        ),
        migrations.RemoveField(
            model_name="history",
            name="old_zone",
        ),
        migrations.AlterField(
            model_name="history",
            name="new_place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_new_place",
                to="warehouse.place",
            ),
        ),
        migrations.AlterField(
            model_name="history",
            name="old_place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="history_old_place",
                to="warehouse.place",
            ),
        ),
    ]
