# Generated by Django 5.2.8 on 2025-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0009_remove_history_new_stock_remove_history_new_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
