# Generated by Django 5.2.8 on 2025-11-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0010_history_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="item",
        ),
        migrations.RemoveField(
            model_name="history",
            name="new_place",
        ),
        migrations.RemoveField(
            model_name="history",
            name="old_place",
        ),
        migrations.AddField(
            model_name="history",
            name="item_code",
            field=models.CharField(default="UNKNOWN_ITEM", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="new_address",
            field=models.CharField(default="1/1/1", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="old_address",
            field=models.CharField(default="2/2/2", max_length=100),
            preserve_default=False,
        ),
    ]
