# Generated by Django 5.2.8 on 2025-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0011_remove_history_item_remove_history_new_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeitem",
            name="full_address",
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
