# Generated by Django 5.2.8 on 2025-11-30 21:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0012_placeitem_full_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={
                "ordering": ["-date"],
                "verbose_name": "История перемещений",
                "verbose_name_plural": "Истории перемещений",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["item_code"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["title"],
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.AlterModelOptions(
            name="placeitem",
            options={
                "ordering": ["pk"],
                "verbose_name": "Ячейка Деталь",
                "verbose_name_plural": "Ячейки Детали",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ["pk"],
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={
                "ordering": ["title"],
                "verbose_name": "Зона",
                "verbose_name_plural": "Зоны",
            },
        ),
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер документа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("planned", "Запланирован"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="Планируемая дата")),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Поставщик"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inbounds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbounds",
                        to="warehouse.stock",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_quantity",
                    models.PositiveIntegerField(verbose_name="Количество в документе"),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Принято"),
                ),
                (
                    "weight_per_unit",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вес за единицу",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("partial", "Частично"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Примечания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "inbound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_items",
                        to="warehouse.inbound",
                        verbose_name="Приход",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.item",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "placement_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_items",
                        to="warehouse.place",
                        verbose_name="Место размещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция прихода",
                "verbose_name_plural": "Позиции прихода",
                "ordering": ["pk"],
                "unique_together": {("inbound", "item")},
            },
        ),
    ]
