# Generated by Django 5.2.8 on 2025-12-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0013_alter_history_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeitem",
            options={
                "ordering": ["pk"],
                "verbose_name": "Сток",
                "verbose_name_plural": "Сток",
            },
        ),
        migrations.RemoveField(
            model_name="inbound",
            name="document_number",
        ),
        migrations.AddField(
            model_name="inbound",
            name="inbound_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Номер поставки",
            ),
        ),
    ]
