# Generated by Django 5.2.8 on 2025-12-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0014_alter_placeitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbounditem",
            name="inbound",
        ),
        migrations.AlterUniqueTogether(
            name="inbounditem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="inbounditem",
            name="item",
        ),
        migrations.RemoveField(
            model_name="inbounditem",
            name="placement_place",
        ),
        migrations.DeleteModel(
            name="Inbound",
        ),
        migrations.DeleteModel(
            name="InboundItem",
        ),
    ]
