# Generated by Django 5.2.8 on 2025-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0015_remove_inbounditem_inbound_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeitem",
            name="STATUS",
            field=models.CharField(
                choices=[
                    ("inbound", "inbound"),
                    ("blk", "block"),
                    ("new", "new"),
                    ("ok", "ok"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
