# Generated by Django 5.2.8 on 2025-12-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0016_alter_placeitem_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="placeitem",
            old_name="STATUS",
            new_name="status",
        ),
    ]
