# Generated by Django 5.2.8 on 2025-12-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bound", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbound",
            name="documents_url",
        ),
        migrations.AlterField(
            model_name="inbound",
            name="created_by",
            field=models.CharField(max_length=100, verbose_name="Создал"),
        ),
    ]
