# Generated by Django 5.2.8 on 2025-12-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bound", "0002_remove_inbound_documents_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbound",
            name="created_by",
            field=models.CharField(
                default="admin", max_length=100, verbose_name="Создал"
            ),
        ),
    ]
