# Generated by Django 5.2.8 on 2025-12-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bound", "0003_alter_inbound_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbound",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Запланирован"),
                    ("in_progress", "В процессе"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
