# Generated by Django 5.2.8 on 2025-12-18 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирован"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="Планируемая дата")),
                (
                    "actual_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Фактическая дата"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waves",
                        to="warehouse.stock",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Волна",
                "verbose_name_plural": "Волны",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaveItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(verbose_name="Количество"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wave_items",
                        to="warehouse.item",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция волны",
                "verbose_name_plural": "Позиции волны",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Inbound",
            fields=[
                (
                    "wave_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wave.wave",
                    ),
                ),
                (
                    "inbound_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Номер поставки",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Поставщик"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставка",
                "verbose_name_plural": "Поставки",
                "ordering": ["-created_at"],
            },
            bases=("wave.wave",),
        ),
        migrations.CreateModel(
            name="Outbound",
            fields=[
                (
                    "wave_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wave.wave",
                    ),
                ),
                (
                    "outbound_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Номер отгрузки",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заказчик"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отгрузка",
                "verbose_name_plural": "Отгрузки",
                "ordering": ["-created_at"],
            },
            bases=("wave.wave",),
        ),
        migrations.CreateModel(
            name="InboundItem",
            fields=[
                (
                    "waveitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wave.waveitem",
                    ),
                ),
                (
                    "inbound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_items",
                        to="wave.inbound",
                        verbose_name="Поставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция поставки",
                "verbose_name_plural": "Позиции поставки",
                "ordering": ["pk"],
            },
            bases=("wave.waveitem",),
        ),
        migrations.CreateModel(
            name="OutboundItem",
            fields=[
                (
                    "waveitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wave.waveitem",
                    ),
                ),
                (
                    "outbound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_items",
                        to="wave.outbound",
                        verbose_name="Отгрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция отгрузки",
                "verbose_name_plural": "Позиции отгрузок",
                "ordering": ["pk"],
            },
            bases=("wave.waveitem",),
        ),
    ]
